import type { Metadata } from "next";
import Navigation from "@/components/Navigation";
import QuoteForm from "@/components/QuoteForm";
import SiteFooter from "@/components/SiteFooter";
import { IconFacebook, IconLocation, IconMail, IconPhone } from "@/lib/icons";

export const metadata: Metadata = { title: "Contact | Blue Sky Painter", description: "Contact Blue Sky Painter in Auckland for a painting project quote." };

export default function ContactPage() { return <><Navigation /><main><section className="bg-brand-bg"><div className="mx-auto max-w-7xl px-6 py-20 lg:px-10 lg:py-28"><div className="overflow-hidden rounded-[2rem] bg-white shadow-[0_30px_80px_-40px_rgba(28,49,99,0.25)]"><div className="grid lg:grid-cols-[0.9fr_1.1fr]"><div className="bg-brand-bg p-8 sm:p-10 lg:p-14"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-brand">Contact</p><h1 className="mt-5 text-4xl font-semibold leading-[0.95] text-navy sm:text-5xl">Get in touch with us <span className="text-brand">today.</span></h1><p className="mt-6 text-base leading-relaxed text-navy/70">Tell us about your painting project and we&apos;ll get back to you with the next steps.</p><div className="mt-10 space-y-6"><a href="tel:+64210362056" className="flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-full bg-navy text-brand-accent"><IconPhone className="h-4 w-4" /></span><span><span className="block text-xs uppercase tracking-wide text-navy/50">Phone</span><span className="text-sm font-medium text-navy">+64 210 362 056</span></span></a><div className="flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-full bg-navy text-brand-accent"><IconLocation className="h-4 w-4" /></span><span><span className="block text-xs uppercase tracking-wide text-navy/50">Location</span><span className="text-sm text-navy">4/35 Highgrove Lane, Totara Vale, Auckland, New Zealand</span></span></div><a href="mailto:info@blueskypainter.co.nz" className="flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-full bg-navy text-brand-accent"><IconMail className="h-4 w-4" /></span><span><span className="block text-xs uppercase tracking-wide text-navy/50">Email</span><span className="text-sm font-medium text-navy">info@blueskypainter.co.nz</span></span></a><a href="#" aria-label="Blue Sky Painter on Facebook (placeholder link)" className="flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-full bg-navy text-brand-accent"><IconFacebook className="h-4 w-4" /></span><span><span className="block text-xs uppercase tracking-wide text-navy/50">Social</span><span className="text-sm font-medium text-navy">Facebook</span></span></a></div></div><div className="p-8 sm:p-10 lg:p-14"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-brand">Request a quote</p><h2 className="mt-3 text-3xl font-semibold text-navy">Tell us about your project</h2><div className="mt-8"><QuoteForm /></div></div></div></div></div></section></main><SiteFooter /></>; }
